### PR TITLE
EVO48, 96, 128 support

### PR DESCRIPTION
**Pull request by yozik04**
Does not load current state yet. Does not react to commands yet.
Loads labels. Syncs time. Reacts to Live Events (Notification part needs work).

Code is splitted to evo and spectra_magellan parts. More parts will move there.

Spectra/Magellan needs to be retested.

### CODE REVIEW

**Comment by jpbarraca** [comment]
It required some minor updates but it seems to work ok. I will leave it running for some time and then we merge.

**Comment by yozik04** [comment]
Great!

Jevgeni

**Comment by jpbarraca** [comment]
I just pushed the changes required for MG/SP
can you please correct the indentation in your commits? 2 vs 4 spaces.

**Comment by yozik04** [comment]
OK. Will do in the evening or tomorrow.

**Comment by yozik04** [comment]
Done

**Pull request merged**
