### PR TITLE
Next iteration

### PR DESCRIPTION
**Pull request by yozik04**

### CODE REVIEW

**Comment by yozik04** [comment]
Actually it merges fine.

**Comment by yozik04** [comment]
Please verify if SP/MG is not broken.

Config file was changed a bit in this commit.

**Comment by yozik04** [comment]
Should we create a dev branch? And merge stable states into master?

**Comment by jpbarraca** [comment]
We should do it to avoid these situations will coping with many changes in what is still a small project.

**Comment by jpbarraca** [comment]
With the latest commit the merge seems to work for MG/SP

**Comment by yozik04** [comment]
Perfect. I merge to **master** and create **dev** branch from **master**. All development needs to be in **dev** from now.

**Comment by yozik04** [comment]
@jpbarraca You forgot to commit _hardware/panel.py_
_process_properties_bulk_ does not exist anywhere. Please check.
I will do merge after you commit.

**Comment by jpbarraca** [comment]
Check that names are consistent for EVO.
The names of the elements (partition, zone, etc...) must be consistent between the parser, paradox.py, the adapter and the mem_map in the panel.

This will be required  to resolve the numbers to actual labels, and in paradox, self.data must have keys for the properties to be resolved (eg, for zone_open, 'zone' must exist in self.data).

Also, do not use Trb as the code explicitly checks for properties with trouble in the name.

**Comment by yozik04** [comment]
Looks good now. Merging.

**Pull request merged**
